---
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)


googlesheets4::gs4_deauth()
sr_protocol <- googlesheets4::read_sheet('https://docs.google.com/spreadsheets/d/1bOwE5sJu0NWfLqh1kVy1U37kRtngvCejYYcbgbGwdHA/edit#gid=992768102', sheet = 'Review protocol')
subheadings <- sr_protocol$"Section / sub-section"
topics <- sr_protocol$Topic
descriptions <- sr_protocol$Description
further_exp <- sr_protocol$"Further explanation"
```

# `r paste0('[', subheadings[1], ']: [', subheadings[2], ']')`  
**`r topics[1]`**: `r descriptions[1]` (`r further_exp[1]`)  
&nbsp;  
&nbsp;  
**`r topics[2]`**: `r descriptions[2]` (`r gsub('\\[1\\]', '', further_exp[2])`[^1])  
&nbsp;  
&nbsp;  

## `r subheadings[3]`  
`r descriptions[3]`  

\newpage

## `r subheadings[4]`
`r descriptions[4]`  
&nbsp;  
&nbsp;  

**Keywords:**  
Use terms that cover the core content of your article. Keywords improve discoverability so it is important to use terms not already mentioned in the title or abstract that will help readers find your paper.  

\newpage

## 1.1 `r subheadings[5]`  
`r descriptions[5]` (`r further_exp[5]`)   
&nbsp;  
&nbsp;  

## 1.2 `r subheadings[6]`  
`r gsub('\\[2\\]', '', descriptions[6])`[^2]  
&nbsp;  
&nbsp;  

## 1.3 `r subheadings[7]`  
**`r topics[7]`**: `r descriptions[7]`  (`r further_exp[7]`) 
&nbsp;  
&nbsp;  
**`r topics[8]`**: `r descriptions[8]`  (`r gsub('\\[3,4\\]', '', further_exp[8])`[^3][^4]) 

\newpage

## 2. `r subheadings[9]` 

### 2.1 `r subheadings[10]` 
**`r topics[10]`**: `r descriptions[10]`  (`r further_exp[10]`)  
&nbsp;  
&nbsp;  
**`r topics[11]`**: `r descriptions[11]`  
&nbsp;  
&nbsp;  
**`r topics[12]`**: `r descriptions[12]`  
&nbsp;  
&nbsp;  
**`r topics[13]`**: `r descriptions[13]`  
&nbsp;  
&nbsp;  
**`r topics[14]`**: `r descriptions[14]`  
&nbsp;  
&nbsp;  
**`r topics[15]`**: `r descriptions[15]`  
&nbsp;  
&nbsp;  
**`r topics[16]`**: `r descriptions[16]`  
&nbsp;  
&nbsp;  
**`r topics[17]`**: `r descriptions[17]`  
&nbsp;  
&nbsp;  
**`r topics[18]`**: `r descriptions[18]`  (`r further_exp[18]`)  

\newpage

### 2.2 `r subheadings[19]` 
**`r topics[19]`**: `r descriptions[19]`  
&nbsp;  
&nbsp;  
**`r topics[20]`**: `r descriptions[20]`  
&nbsp;  
&nbsp;  
**`r topics[21]`**: `r descriptions[21]`  
&nbsp;  
&nbsp;  
**`r topics[22]`**: `r descriptions[22]`  
&nbsp;  
&nbsp;  

\newpage

### 2.3 `r subheadings[23]` 
**`r topics[23]`**: `r descriptions[23]`  
&nbsp;  
&nbsp;  
**`r topics[24]`**: `r descriptions[24]`  
&nbsp;  
&nbsp;  
**`r topics[25]`**: `r descriptions[25]`  
&nbsp;  
&nbsp;  

\newpage

### 2.4 `r subheadings[26]` 
**`r topics[26]`**: `r descriptions[26]`  
&nbsp;  
&nbsp;  
**`r topics[27]`**: `r descriptions[27]`  
&nbsp;  
&nbsp;  
**`r topics[28]`**: `r descriptions[28]`  
&nbsp;  
&nbsp;  
**`r topics[29]`**: `r descriptions[29]`  
&nbsp;  
&nbsp;  

\newpage

### 2.5 `r subheadings[30]` 
`r descriptions[30]`  (`r further_exp[30]`)  

\newpage

### 2.6 `r subheadings[31]` 
**`r topics[31]`**: `r descriptions[31]`  
&nbsp;  
&nbsp;  
**`r topics[32]`**: `r descriptions[32]`  (`r further_exp[32]`)  
&nbsp;  
&nbsp;  
**`r topics[33]`**: `r descriptions[33]`  (`r further_exp[33]`)  
&nbsp;  
&nbsp;  
**`r topics[34]`**: `r descriptions[34]`  (`r further_exp[34]`)  
&nbsp;  
&nbsp;  
**`r topics[35]`**: `r descriptions[35]`  (`r further_exp[35]`)  
&nbsp;  
&nbsp;  
**`r topics[36]`**: `r descriptions[36]`  (`r further_exp[36]`)  
&nbsp;  
&nbsp;  
**`r topics[37]`**: `r descriptions[37]`  (`r further_exp[37]`)  
&nbsp;  
&nbsp;  
**`r topics[38]`**: `r descriptions[38]`  (`r further_exp[38]`)  

\newpage

### 2.6 `r subheadings[39]` 
**`r topics[39]`**: `r descriptions[39]`  


[^1]: Bayliss, H.R., Haddaway, N.R., Eales, J., Frampton, G.K. and James, K.L., 2016. Updating and amending systematic reviews and systematic maps in environmental management. Environmental Evidence, 5(1), p.20.  
[^2]: Haddaway, N.R., Kohl, C., da Silva, N.R., Schiemann, J., Spök, A., Stewart, R., Sweet, J.B. and Wilhelm, R., 2017. A framework for stakeholder engagement during systematic reviews and maps in environmental management. Environmental Evidence, 6(1), p.11.  
[^3]: Collaboration for Environmental Evidence. 2018. Guidelines and Standards for Evidence synthesis in Environmental Management. Version 5.0. www.environmentalevidence.org/information-for-authors.
[^4]: Leeds Institute of Health Sciences. https://medhealth.leeds.ac.uk/info/639/information_specialists/1500/search_concept_tools. Accessed 12/11/2017.
